version: '3.9'

services:
  nodered:
    image: nodered/node-red:latest
    environment:
      - TZ=America/Bogota
    ports:
      - "1880:1880"
      - "1883:1883"
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./nodered_data
        target: /data

  mysql:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=IO-Link-data
      - MYSQL_USER=jclondono
      - MYSQL_PASSWORD=Elico2024-
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./mariadb_data
        target: /var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=10000M
    depends_on:
      - mysql