version: '3.9'

services:
  nodered:
    image: nodered/node-red
    environment:
      - TZ=America/Bogota
    ports:
      - "1880:1880"
    restart: always
    volumes:
      - type: bind
        source: ./nodered_data
        target: /data
  
  mosquitto:
   image: eclipse-mosquitto
   container_name: mosquitto
   environment:
     - TZ=America/Bogota
   ports:
     - "1883:1883"
     - "9001:9001"
   restart: unless-stopped
   volumes:
     - type: bind
       source: ./mosquitto/config
       target: /mosquitto/config
     - type: bind
       source: ./mosquitto/data
       target: /mosquitto/data
     - type: bind
       source: ./mosquitto/log
       target: /mosquitto/log
