version: '3.9'

services:    
  nodered:
    image: nodered/node-red
    environment:
      - TZ=America/Bogota
    ports:
      - "1880:1880"
      - "1883:1883"
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./nodered_data
        target: /data